[hekad]
maxprocs=10

[DashboardOutput]

[systemslogs]
type = "LogstreamerInput"
log_directory = "/var/log/syslog/systems"
file_match = '(?P<Year>\d+)-(?P<Month>\d+)-(?P<Day>\d+).log'
priority = ["Year","Month","Day"]
oldest_duration = "2h"
decoder = "systemslogs_transform_decoder"

[systemslogs_transform_decoder]
type = "SandboxDecoder"
script_type = "lua"
filename = "syslog_tab_delimited.lua"

[systemslogs_transform_decoder.config]
type='syslog'

# Start commenting here if you don't want any stdout
[stdout]
type = "LogOutput"
message_matcher = "TRUE"
#payload_only = true
# Finish commenting here


[ESJsonEncoder]
index = "events"
es_index_from_timestamp = false
type_name = "event"

[ElasticSearchOutput]
message_matcher = "Type!='heka.all-report'"
encoder = "ESJsonEncoder"
server = "http://mozdef.example.com:8080"
flush_interval = 1000
flush_count = 10